# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 19:54
from __future__ import unicode_literals

import audiofield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audiogallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myaudiofile',
            name='audio_file',
            field=audiofield.fields.AudioField(help_text='Allowed type - .mp3, .wav, .ogg', upload_to='api'),
        ),
    ]
