# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiogallery', '0003_auto_20171218_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='myaudiofile',
            name='ivector',
            field=models.TextField(null=True),
        ),
    ]
